--getNoticeList
SELECT ROWNUM, NOTICE.* FROM notice ORDER BY CREATE_DATE DESC;

SELECT * FROM (
    SELECT ROWNUM NUM, N.* FROM (
    SELECT * FROM NOTICE ORDER BY CREATE_DATE DESC) N
) WHERE NUM BETWEEN 6 AND 10;


--getNoticeCount
SELECT COUNT(*) FROM NOTICE;

--getNotice
SELECT * FROM NOTICE WHERE NO=4;

--getNextNotice
SELECT * FROM NOTICE WHERE NO=(
    SELECT NO FROM NOTICE WHERE CREATE_DATE>(
        SELECT CREATE_DATE FROM NOTICE WHERE NO=3) AND ROWNUM = 1);

--getPrevNotice
SELECT * FROM NOTICE WHERE NO=(
    SELECT NO FROM (SELECT * FROM NOTICE ORDER BY CREATE_DATE DESC)
        WHERE CREATE_DATE<(SELECT CREATE_DATE FROM NOTICE WHERE NO=3)
        AND ROWNUM = 1);
SELECT NO FROM (SELECT * FROM NOTICE ORDER BY CREATE_DATE DESC)
        WHERE CREATE_DATE<(SELECT CREATE_DATE FROM NOTICE WHERE NO=3)
